CREATE DATABASE coffee_table;

CREATE TABLE users(
  _id int NOT NULL AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  forename VARCHAR(32) NOT NULL,
  surname VARCHAR(64) NOT NULL,
  role VARCHAR(10) NOT NULL, /* WRITER, PUBLISHER, ADMIN, USER */
  PRIMARY KEY(_id)
);
